export const DHAKA_THANAS = [
  "Adabor",
  "Badda",
  "Bangsal",
  "Bimanbandar",
  "Cantonment",
  "Chowkbazar",
  "Darus Salam",
  "Demra",
  "Dhanmondi",
  "Gendaria",
  "Gulshan",
  "Hazaribagh",
  "Kadamtali",
  "Kafrul",
  "Kalabagan",
  "Kamrangirchar",
  "Khilgaon",
  "Khilkhet",
  "Kotwali",
  "Lalbagh",
  "Mirpur (Model)",
  "Mohammadpur",
  "Motijheel",
  "New Market",
  "Pallabi",
  "Paltan",
  "Panthapath",
  "Ramna",
  "Rampura",
  "Sabujbagh",
  "Shah Ali",
  "Shahbagh",
  "Sher-e-Bangla Nagar",
  "Shyampur",
  "Sutrapur",
  "Tejgaon",
  "Tejgaon Industrial Area",
  "Turag",
  "Uttara",
  "Uttar Khan",
  "Vatara",
  "Wari"
];
